language: ruby
cache: bundler
rvm:
  - 2.2.2
  - jruby
  - rbx-2
gemfile:
  - gemfiles/ar50.gemfile
allow_failures:
  - jruby
  - rbx-2
before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev
