language: ruby
cache: bundler
rvm:
  - 2.2.2
  - jruby
  - rbx-2
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev
